# Fonte de dados:
spring.datasource.url=${DATASOURCE_URL:jdbc:mysql://localhost:3306/seagri}?createDatabaseIfNotExist=true&ssl-mode=REQUIRED
spring.datasource.username=${DATASOURCE_USERNAME:root}
spring.datasource.password=${DATASOURCE_PASSWORD:}

# JPA/Hibernate/ORM:
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=6qfR9uV2xW4zK8nP1sT7mY3aC5dH0jL4bN9eQ2rU6iO1pA8fG3kM7tV5yX0zC4
